const mockGames = 
{
  "data": [
      {
          "id": "1",
          "type": "board_games",
          "attributes": {
              "bgg_id": 224517,
              "title": "Brass: Birmingham",
              "image_path": "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxH41Y6_ROoePAilPNEhXnzO8=/0x0/filters:format(jpeg)/pic3490053.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 120,
              "categories": "Age of Reason, Economic, Industry / Manufacturing, Post-Napoleonic, Trains, Transportation",
              "cooperative": false,
              "description": "Brass: Birmingham is an economic strategy game sequel to Martin Wallace' 2007 masterpiece, Brass. Brass: Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution, between the years of 1770-1870.&#10;&#10;It offers a very different story arc and experience from its predecessor. As in its predecessor, you must develop, build, and establish your industries and network, in an effort to exploit low or high market demands. The game is played over two halves: the canal era (years 1770-1830) and the rail era (years 1830-1870). To win the game, score the most VPs. VPs are counted at the end of each half for the canals, rails and established (flipped) industry tiles.&#10;&#10;Each round, players take turns according to the turn order track, receiving two actions to perform any of the following actions (found in the original game):&#10;&#10;1) Build - Pay required resources and place an industry tile.&#10;2) Network - Add a rail / canal link, expanding your network.&#10;3) Develop - Increase the VP value of an industry.&#10;4) Sell - Sell your cotton, manufactured goods and pottery.&#10;5) Loan - Take a &pound;30 loan and reduce your income.&#10;&#10;Brass: Birmingham also features a new sixth action:&#10;&#10;6) Scout - Discard three cards and take a wild location and wild industry card. (This action replaces Double Action Build in original Brass.)&#10;&#10;",
              "rating": 8.42201,
              "year_published": 2018,
              "rank": 1,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 1,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "2",
          "type": "board_games",
          "attributes": {
              "bgg_id": 161936,
              "title": "Pandemic Legacy: Season 1",
              "image_path": "https://cf.geekdo-images.com/-Qer2BBPG7qGGDu6KcVDIw__original/img/PlzAH7swN1nsFxOXbfUvE3TkE5w=/0x0/filters:format(png)/pic2452831.png",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 60,
              "categories": "Environmental, Medical",
              "cooperative": true,
              "description": "Pandemic Legacy is a co-operative campaign game, with an overarching story-arc played through 12-24 sessions, depending on how well your group does at the game. At the beginning, the game starts very similar to basic Pandemic, in which your team of disease-fighting specialists races against the clock to travel around the world, treating disease hotspots while researching cures for each of four plagues before they get out of hand.&#10;&#10;During a player's turn, they have four actions available, with which they may travel around in the world in various ways (sometimes needing to discard a card), build structures like research stations, treat diseases (removing one cube from the board; if all cubes of a color have been removed, the disease has been eradicated), trade cards with other players, or find a cure for a disease (requiring five cards of the same color to be discarded while at a research station). Each player has a unique role with special abilities to help them at these actions.&#10;&#10;After a player has taken their actions, they draw two cards. These cards can include epidemic cards, which will place new disease cubes on the board, and can lead to an outbreak, spreading disease cubes even further. Outbreaks additionally increase the panic level of a city, making that city more expensive to travel to.&#10;&#10;Each month in the game, you have two chances to achieve that month's objectives. If you succeed, you win and immediately move on to the next month. If you fail, you have a second chance, with more funding for beneficial event cards.&#10;&#10;During the campaign, new rules and components will be introduced. These will sometimes require you to permanently alter the components of the game; this includes writing on cards, ripping up cards, and placing permanent stickers on components. Your characters can gain new skills, or detrimental effects. A character can even be lost entirely, at which point it's no longer available for play.&#10;&#10;Part of the Pandemic series&#10;&#10;",
              "rating": 8.38609,
              "year_published": 2015,
              "rank": 2,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 2,
              "thematic_rank": 1,
              "wargames_rank": null
          }
      },
      {
          "id": "3",
          "type": "board_games",
          "attributes": {
              "bgg_id": 174430,
              "title": "Gloomhaven",
              "image_path": "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__original/img/7d-lj5Gd1e8PFnD97LYFah2c45M=/0x0/filters:format(jpeg)/pic2437871.jpg",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 120,
              "categories": "Adventure, Exploration, Fantasy, Fighting, Miniatures",
              "cooperative": true,
              "description": "Gloomhaven  is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world. Players must work together out of necessity to clear out menacing dungeons and forgotten ruins. In the process, they will enhance their abilities with experience and loot, discover new locations to explore and plunder, and expand an ever-branching story fueled by the decisions they make.&#10;&#10;This is a game with a persistent and changing world that is ideally played over many game sessions. After a scenario, players will make decisions on what to do, which will determine how the story continues, kind of like a &ldquo;Choose Your Own Adventure&rdquo; book. Playing through a scenario is a cooperative affair where players will fight against automated monsters using an innovative card system to determine the order of play and what a player does on their turn.&#10;&#10;Each turn, a player chooses two cards to play out of their hand. The number on the top card determines their initiative for the round. Each card also has a top and bottom power, and when it is a player&rsquo;s turn in the initiative order, they determine whether to use the top power of one card and the bottom power of the other, or vice-versa. Players must be careful, though, because over time they will permanently lose cards from their hands. If they take too long to clear a dungeon, they may end up exhausted and be forced to retreat.&#10;&#10;",
              "rating": 8.37321,
              "year_published": 2017,
              "rank": 3,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 4,
              "thematic_rank": 2,
              "wargames_rank": null
          }
      },
      {
          "id": "4",
          "type": "board_games",
          "attributes": {
              "bgg_id": 342942,
              "title": "Ark Nova",
              "image_path": "https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__original/img/g4S18szTdrXCdIwVKzMKrZrYAcM=/0x0/filters:format(jpeg)/pic6293412.jpg",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 90,
              "max_playtime": 150,
              "categories": "Animals, Economic, Environmental",
              "cooperative": false,
              "description": "In Ark Nova, you will plan and design a modern, scientifically managed zoo. With the ultimate goal of owning the most successful zoological establishment, you will build enclosures, accommodate animals, and support conservation projects all over the world. Specialists and unique buildings will help you in achieving this goal.&#10;&#10;Each player has a set of five action cards to manage their gameplay, and the power of an action is determined by the slot the card currently occupies. The cards in question are:&#10;&#10;&#10;    CARDS: Allows you to gain new zoo cards (animals, sponsors, and conservation project cards).&#10;    BUILD: Allows you to build standard or special enclosures, kiosks, and pavilions.&#10;    ANIMALS: Allows you to accommodate animals in your zoo.&#10;    ASSOCIATION: Allows your association workers to carry out different tasks.&#10;    SPONSORS: Allows you to play a sponsor card in your zoo or to raise money.&#10;&#10;&#10;255 cards featuring animals, specialists, special enclosures, and conservation projects, each with a special ability, are at the heart of Ark Nova. Use them to increase the appeal and scientific reputation of your zoo and collect conservation points.&#10;&#10;&mdash;description from the publisher&#10;&#10;",
              "rating": 8.32054,
              "year_published": 2021,
              "rank": 4,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 3,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "5",
          "type": "board_games",
          "attributes": {
              "bgg_id": 233078,
              "title": "Twilight Imperium: Fourth Edition",
              "image_path": "https://cf.geekdo-images.com/_Ppn5lssO5OaildSE-FgFA__original/img/kVpZ0Maa_LeQGWxOqsYKP3N4KUY=/0x0/filters:format(jpeg)/pic3727516.jpg",
              "min_players": 3,
              "max_players": 6,
              "min_playtime": 240,
              "max_playtime": 480,
              "categories": "Civilization, Economic, Exploration, Negotiation, Political, Science Fiction, Space Exploration, Wargame",
              "cooperative": false,
              "description": "Twilight Imperium (Fourth Edition) is a game of galactic conquest in which three to six players take on the role of one of seventeen factions vying for galactic domination through military might, political maneuvering, and economic bargaining. Every faction offers a completely different play experience, from the wormhole-hopping Ghosts of Creuss to the Emirates of Hacan, masters of trade and economics. These seventeen races are offered many paths to victory, but only one may sit upon the throne of Mecatol Rex as the new masters of the galaxy. No two games of Twilight Imperium are ever identical. At the start of each galactic age, the game board is uniquely and strategically constructed using 51 galaxy tiles that feature everything from lush new planets and supernovas to asteroid fields and gravity rifts. Players are dealt a hand of these tiles and take turns creating the galaxy around Mecatol Rex, the capital planet seated in the center of the board. An ion storm may block your race from progressing through the galaxy while a fortuitously placed gravity rift may protect you from your closest foes. The galaxy is yours to both craft and dominate. A round of Twilight Imperium begins with players selecting one of eight strategy cards that both determine player order and give their owner a unique strategic action for that round. These may do anything from providing additional command tokens to allowing a player to control trade throughout the galaxy. After these roles are selected, players take turns moving their fleets from system to system, claiming new planets for their empire, and engaging in warfare and trade with other factions. At the end of a turn, players gather in a grand council to pass new laws and agendas, shaking up the game in unpredictable ways.&#10;&#10;After every player has passed their turn, players move up the victory track by checking to see whether they have completed any objectives throughout the turn and scoring them. Objectives are determined by setting up ten public objective cards at the start of each game, then gradually revealing them with every round. Every player also chooses between two random secret objectives at the start of the game, providing victory points achievable only by the holder of that objective. These objectives can be anything from researching new technologies to taking your neighbor's home system. At the end of every turn, a player can claim one public objective and one secret objective. As play continues, more of these objectives are revealed and more secret objectives are dealt out, giving players dynamically changing goals throughout the game. Play continues until a player reaches ten victory points.",
              "rating": 8.24213,
              "year_published": 2017,
              "rank": 5,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 5,
              "thematic_rank": 3,
              "wargames_rank": null
          }
      },
      {
          "id": "6",
          "type": "board_games",
          "attributes": {
              "bgg_id": 167791,
              "title": "Terraforming Mars",
              "image_path": "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/thIqWDnH9utKuoKVEUqveDixprI=/0x0/filters:format(jpeg)/pic3536616.jpg",
              "min_players": 1,
              "max_players": 5,
              "min_playtime": 120,
              "max_playtime": 120,
              "categories": "Economic, Environmental, Industry / Manufacturing, Science Fiction, Space Exploration, Territory Building",
              "cooperative": false,
              "description": "In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable. In Terraforming Mars, you play one of those corporations and work together in the terraforming process, but compete for getting victory points that are awarded not only for your contribution to the terraforming, but also for advancing human infrastructure throughout the solar system, and doing other commendable things. The players acquire unique project cards (from over two hundred different ones) by buying them to their hand. The cards can give you immediate bonuses, as well as increasing your production of different resources. Many cards also have requirements and they become playable when the temperature, oxygen, or ocean coverage increases enough. Buying cards is costly, so there is a balance between buying cards and actually playing them. Standard Projects are always available to complement your cards. Your basic income, as well as your basic score, is based on your Terraform Rating. However, your income is complemented with your production, and you also get VPs from many other sources. Each player keeps track of their production and resources on their player boards, and the game uses six types of resources: MegaCredits, Steel, Titanium, Plants, Energy, and Heat. On the game board, you compete for the best places for your city tiles, ocean tiles, and greenery tiles. You also compete for different Milestones and Awards worth many VPs. Each round is called a generation and consists of the following phases:&#10;&#10;1) Player order shifts clockwise.&#10;2) Research phase: All players buy cards from four privately drawn.&#10;3) Action phase: Players take turns doing 1-2 actions from these options: Playing a card, claiming a Milestone, funding an Award, using a Standard project, converting plant into greenery tiles (and raising oxygen), converting heat into a temperature raise, and using the action of a card in play. The turn continues around the table (sometimes several laps) until all players have passed.&#10;4) Production phase: Players get resources according to their terraform rating and production parameters.&#10;&#10;When the three global parameters (temperature, oxygen, ocean) have all reached their goal, the terraforming is complete, and the game ends after that generation. Count your Terraform Rating and other VPs to determine the winning corporation!&#10;&#10;",
              "rating": 8.22183,
              "year_published": 2016,
              "rank": 6,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 7,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "7",
          "type": "board_games",
          "attributes": {
              "bgg_id": 316554,
              "title": "Dune: Imperium",
              "image_path": "https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__original/img/mZzaBAEEJpMlHWWmC0R6Su0OibQ=/0x0/filters:format(jpeg)/pic5666597.jpg",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 120,
              "categories": "Movies / TV / Radio theme, Novel-based, Political, Science Fiction",
              "cooperative": false,
              "description": "Dune: Imperium is a game that uses deck-building to add a hidden-information angle to traditional worker placement. It finds inspiration in elements and characters from the Dune legacy, both the new film from Legendary Pictures and the seminal literary series from Frank Herbert, Brian Herbert, and Kevin J. Anderson.&#10;&#10;As a leader of one of the Great Houses of the Landsraad, raise your banner and marshal your forces and spies. War is coming, and at the center of the conflict is Arrakis &ndash; Dune, the desert planet.&#10;&#10;You start with a unique leader card, as well as a deck identical to those of your opponents.  As you acquire cards and build your deck, your choices will define your strengths and weaknesses. Cards allow you to send your Agents to certain spaces on the game board, so how your deck evolves affects your strategy. You might become more powerful militarily, able to deploy more troops than your opponents. Or you might acquire cards that give you an edge with the four political factions represented in the game: the Emperor, the Spacing Guild, the Bene Gesserit, and the Fremen.&#10;&#10;Unlike many deck-building games, you don&rsquo;t play your entire hand in one turn. Instead, you draw a hand of cards at the start of every round and alternate with other players, taking one Agent turn at a time (playing one card to send one of your Agents to the game board). When it&rsquo;s your turn and you have no more Agents to place, you&rsquo;ll take a Reveal turn, revealing the rest of your cards, which will provide Persuasion and Swords. Persuasion is used to acquire more cards, and Swords help your troops fight for the current round&rsquo;s rewards as shown on the revealed Conflict card.&#10;&#10;Defeat your rivals in combat, shrewdly navigate the political factions, and acquire precious cards. The Spice must flow to lead your House to victory!&#10;&#10;Some important links: The Official FAQ, the Unofficial FAQ, and an Automa (solo and 2p) Overview&#10;&#10;",
              "rating": 8.20863,
              "year_published": 2020,
              "rank": 7,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 6,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "8",
          "type": "board_games",
          "attributes": {
              "bgg_id": 291457,
              "title": "Gloomhaven: Jaws of the Lion",
              "image_path": "https://cf.geekdo-images.com/_HhIdavYW-hid20Iq3hhmg__original/img/PBzsLRqNKQKJxGnzpb7o3qLWPQM=/0x0/filters:format(jpeg)/pic5055631.jpg",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 30,
              "max_playtime": 120,
              "categories": "Adventure, Exploration, Fantasy, Fighting, Miniatures",
              "cooperative": true,
              "description": "Gloomhaven: Jaws of the Lion is a standalone game that takes place before the events of Gloomhaven. The game includes four new characters &mdash; Valrath Red Guard (tank, crowd control), Inox Hatchet (ranged damage), Human Voidwarden (support, mind-control), and Quatryl Demolitionist (melee damage, obstacle manipulation) &mdash; that can also be used in the original Gloomhaven game.&#10;&#10;The game also includes 16 monster types (including seven new standard monsters and three new bosses) and a new campaign with 25 scenarios that invites the heroes to investigate a case of mysterious disappearances within the city. Is it the work of Vermlings, or is something far more sinister going on?&#10;&#10;Gloomhaven: Jaws of the Lion is aimed at a more casual audience to get people into the gameplay more quickly. All of the hard-to-organize cardboard map tiles have been removed, and instead players will play on the scenario book itself, which features new artwork unique to each scenario. The last barrier to entry &mdash; i.e., learning the game &mdash; has also been lowered through a simplified rule set and a five-scenario tutorial that will ease new players into the experience.&#10;&#10;",
              "rating": 8.18962,
              "year_published": 2020,
              "rank": 8,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 9,
              "thematic_rank": 6,
              "wargames_rank": null
          }
      },
      {
          "id": "9",
          "type": "board_games",
          "attributes": {
              "bgg_id": 115746,
              "title": "War of the Ring: Second Edition",
              "image_path": "https://cf.geekdo-images.com/ImPgGag98W6gpV1KV812aA__original/img/38jB7fN07DwlrGKYAf-J0vsNdgs=/0x0/filters:format(jpeg)/pic1215633.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 150,
              "max_playtime": 180,
              "categories": "Adventure, Fantasy, Fighting, Novel-based, Territory Building, Wargame",
              "cooperative": false,
              "description": "In War of the Ring, one player takes control of the Free Peoples (FP), the other player controls Shadow Armies (SA). Initially, the Free People Nations are reluctant to take arms against Sauron, so they must be attacked by Sauron or persuaded by Gandalf or other Companions, before they start to fight properly: this is represented by the Political Track, which shows if a Nation is ready to fight in the War of the Ring or not.&#10;&#10;The game can be won by a military victory, if Sauron conquers a certain number of Free People cities and strongholds or vice versa. But the true hope of the Free Peoples lies with the quest of the Ringbearer: while the armies clash across Middle Earth, the Fellowship of the Ring is trying to get secretly to Mount Doom to destroy the One Ring. Sauron is not aware of the real intention of his enemies but is looking across Middle Earth for the precious Ring, so that the Fellowship is going to face numerous dangers, represented by the rules of The Hunt for the Ring. But the Companions can spur the Free Peoples to the fight against Sauron, so the Free People player must balance the need to protect the Ringbearer from harm, against the attempt to raise a proper defense against the armies of the Shadow, so that they do not overrun Middle Earth before the Ringbearer completes his quest.&#10;&#10;Each game turn revolves around the roll of Action Dice: each die corresponds to an action that a player can do during a turn. Depending on the face rolled on each die, different actions are possible (moving armies, characters, recruiting troops, advancing a Political Track).&#10;&#10;Action Dice can also be used to draw or play Event Cards. Event Cards are played to represent specific events from the story (or events that could possibly have happened) that cannot be portrayed through normal game-play. Each Event Card can also create an unexpected turn in the game, allowing special actions or altering the course of a battle.&#10;&#10;",
              "rating": 8.18019,
              "year_published": 2011,
              "rank": 9,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": null,
              "thematic_rank": 4,
              "wargames_rank": 1
          }
      },
      {
          "id": "10",
          "type": "board_games",
          "attributes": {
              "bgg_id": 187645,
              "title": "Star Wars: Rebellion",
              "image_path": "https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__original/img/GKueTbkCk2Ramf6ai8mDj-BP6cI=/0x0/filters:format(jpeg)/pic4325841.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 180,
              "max_playtime": 240,
              "categories": "Civil War, Miniatures, Movies / TV / Radio theme, Science Fiction, Space Exploration, Wargame",
              "cooperative": false,
              "description": "Star Wars: Rebellion is a board game of epic conflict between the Galactic Empire and Rebel Alliance for two to four players.&#10;&#10;Experience the Galactic Civil War like never before. In Rebellion, you control the entire Galactic Empire or the fledgling Rebel Alliance. You must command starships, account for troop movements, and rally systems to your cause. Given the differences between the Empire and Rebel Alliance, each side has different win conditions, and you'll need to adjust your play style depending on who you represent:&#10;&#10;     As the Imperial player, you can command legions of Stormtroopers, swarms of TIEs, Star Destroyers, and even the Death Star. You rule the galaxy by fear, relying on the power of your massive military to enforce your will. To win the game, you need to snuff out the budding Rebel Alliance by finding its base and obliterating it. Along the way, you can subjugate worlds or even destroy them.&#10;     As the Rebel player, you can command dozens of troopers, T-47 airspeeders, Corellian corvettes, and fighter squadrons. However, these forces are no match for the Imperial military. In terms of raw strength, you'll find yourself clearly overmatched from the very outset, so you'll need to rally the planets to join your cause and execute targeted military strikes to sabotage Imperial build yards and steal valuable intelligence. To win the Galactic Civil War, you'll need to sway the galaxy's citizens to your cause. If you survive long enough and strengthen your reputation, you inspire the galaxy to a full-scale revolt, and you win.&#10;&#10;&#10;Featuring more than 150 plastic miniatures and two game boards that account for thirty-two of the Star Wars galaxy's most notable systems, Rebellion features a scope that is as large and sweeping as any Star Wars game before it.&#10;&#10;Yet for all its grandiosity, Rebellion remains intensely personal, cinematic, and heroic. As much as your success depends upon the strength of your starships, vehicles, and troops, it depends upon the individual efforts of such notable characters as Leia Organa, Mon Mothma, Grand Moff Tarkin, and Emperor Palpatine. As civil war spreads throughout the galaxy, these leaders are invaluable to your efforts, and the secret missions they attempt will evoke many of the most inspiring moments from the classic trilogy. You might send Luke Skywalker to receive Jedi training on Dagobah or have Darth Vader spring a trap that freezes Han Solo in carbonite!&#10;&#10;",
              "rating": 8.17088,
              "year_published": 2016,
              "rank": 10,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": null,
              "thematic_rank": 5,
              "wargames_rank": null
          }
      },
      {
          "id": "11",
          "type": "board_games",
          "attributes": {
              "bgg_id": 162886,
              "title": "Spirit Island",
              "image_path": "https://cf.geekdo-images.com/kjCm4ZvPjIZxS-mYgSPy1g__original/img/9uLd9C3XAvInLCLhAoXqKVk56zs=/0x0/filters:format(jpeg)/pic7013651.jpg",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 90,
              "max_playtime": 120,
              "categories": "Fantasy, Fighting, Mythology, Territory Building",
              "cooperative": true,
              "description": "In the most distant reaches of the world, magic still exists, embodied by spirits of the land, of the sky, and of every natural thing. As the great powers of Europe stretch their colonial empires further and further, they will inevitably lay claim to a place where spirits still hold power - and when they do, the land itself will fight back alongside the islanders who live there.&#10;&#10;Spirit Island is a complex and thematic cooperative game about defending your island home from colonizing Invaders. Players are different spirits of the land, each with its own unique elemental powers. Every turn, players simultaneously choose which of their power cards to play, paying energy to do so. Using combinations of power cards that match a spirit's elemental affinities can grant free bonus effects. Faster powers take effect immediately, before the Invaders spread and ravage, but other magics are slower, requiring forethought and planning to use effectively. In the Spirit phase, spirits gain energy, and choose how / whether to Grow: to reclaim used power cards, to seek for new power, or to spread presence into new areas of the island.&#10;&#10;The Invaders expand across the island map in a semi-predictable fashion. Each turn they explore into some lands (portions of the island); the next turn, they build in those lands, forming settlements and cities. The turn after that, they ravage there, bringing blight to the land and attacking any native islanders present. The islanders fight back against the Invaders when attacked, and lend the spirits some other aid, but may not always do so exactly as you'd hoped. Some Powers work through the islanders, helping them (eg) drive out the Invaders or clean the land of blight.&#10;&#10;The game escalates as it progresses: spirits spread their presence to new parts of the island and seek out new and more potent powers, while the Invaders step up their colonization efforts. Each turn represents 1-3 years of alternate-history. At game start, winning requires destroying every last settlement and city on the board - but as you frighten the Invaders more and more, victory becomes easier: they'll run away even if some number of settlements or cities remain. Defeat comes if any spirit is destroyed, if the island is overrun by blight, or if the Invader deck is depleted before achieving victory.&#10;&#10;The game includes different adversaries to fight against (eg: a Swedish Mining Colony, or a Remote British Colony). Each changes play in different ways, and offers a different path of difficulty boosts to keep the game challenging as you gain skill.&#10;&#10;",
              "rating": 8.15077,
              "year_published": 2017,
              "rank": 11,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 10,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "12",
          "type": "board_games",
          "attributes": {
              "bgg_id": 220308,
              "title": "Gaia Project",
              "image_path": "https://cf.geekdo-images.com/hGWFm3hbMlCDsfCsauOQ4g__original/img/tjlflQtUPFiTpLpwk1NCVCS29Ic=/0x0/filters:format(png)/pic5375625.png",
              "min_players": 1,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 150,
              "categories": "Civilization, Economic, Miniatures, Science Fiction, Space Exploration, Territory Building",
              "cooperative": false,
              "description": "Gaia Project is a new game in the line of Terra Mystica. As in the original Terra Mystica, fourteen different factions live on seven different kinds of planets, and each faction is bound to their own home planets, so to develop and grow, they must terraform neighboring planets into their home environments in competition with the other groups. In addition, Gaia planets can be used by all factions for colonization, and Transdimensional planets can be changed into Gaia planets.&#10;&#10;All factions can improve their skills in six different areas of development &mdash; Terraforming, Navigation, Artificial Intelligence, Gaiaforming, Economy, Research &mdash; leading to advanced technology and special bonuses. To do all of that, each group has special skills and abilities.&#10;&#10;The playing area is made of ten sectors, allowing a variable set-up and thus an even bigger replay value than its predecessor Terra Mystica. A two-player game is hosted on seven sectors.&#10;&#10;&mdash;description from the publisher&#10;&#10;",
              "rating": 8.12937,
              "year_published": 2017,
              "rank": 12,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 8,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "13",
          "type": "board_games",
          "attributes": {
              "bgg_id": 12333,
              "title": "Twilight Struggle",
              "image_path": "https://cf.geekdo-images.com/pNCiUUphnoeWOYfsWq0kng__original/img/Iae47UtAd_RXVd5tJ3YzbDHOv4E=/0x0/filters:format(jpeg)/pic3530661.jpg",
              "min_players": 2,
              "max_players": 2,
              "min_playtime": 120,
              "max_playtime": 180,
              "categories": "Modern Warfare, Political, Wargame",
              "cooperative": false,
              "description": "&quot;Now the trumpet summons us again, not as a call to bear arms, though arms we need; not as a call to battle, though embattled we are &ndash; but a call to bear the burden of a long twilight struggle...&quot;&#10;&ndash; John F. Kennedy&#10;&#10;In 1945, unlikely allies toppled Hitler's war machine, while humanity's most devastating weapons forced the Japanese Empire to its knees in a storm of fire. Where once there stood many great powers, there then stood only two. The world had scant months to sigh its collective relief before a new conflict threatened. Unlike the titanic struggles of the preceding decades, this conflict would be waged not primarily by soldiers and tanks, but by spies and politicians, scientists and intellectuals, artists and traitors. Twilight Struggle is a two-player game simulating the forty-five year  dance of intrigue, prestige, and occasional flares of warfare between the Soviet Union and the United States. The entire world is the stage on which these two titans fight to make the world safe for their own ideologies and ways of life. The game begins amidst the ruins of Europe as the two new &quot;superpowers&quot; scramble over the wreckage of the Second World War, and ends in 1989, when only the United States remained standing.&#10;&#10;Twilight Struggle inherits its fundamental systems from the card-driven classics We the People and Hannibal: Rome vs. Carthage. It is a quick-playing, low-complexity game in that tradition. The game map is a world map of the period, whereon players move units and exert influence in attempts to gain allies and control for their superpower. As with GMT's other card-driven games, decision-making is a challenge; how to best use one's cards and units given consistently limited resources?&#10;&#10;Twilight Struggle's Event cards add detail and flavor to the game. They cover a vast array of historical happenings, from the Arab-Israeli conflicts of 1948 and 1967, to Vietnam and the U.S. peace movement, to the Cuban Missile Crisis and other such incidents that brought the world to the brink of nuclear annihilation. Subsystems capture the prestige-laden Space Race as well as nuclear tensions, with the possibility of game-ending nuclear war.&#10;&#10;Components (original edition):&#10;&#10;&#10;     228 full colour counters &#10;     22&quot;x34&quot; full colour map &#10;     103 event cards &#10;     2 six-sided dice&#10;     1 24-page rulebook&#10;     2 full colour player aid cards&#10;&#10;&#10;Components (2009 Deluxe edition and after)&#10;&#10;     260 full colour counters &#10;     22&quot;x34&quot; mounted map with revised graphics&#10;     110 event cards&#10;     2 six-sided dice&#10;     1 24-page rulebook&#10;     2 full colour player aid cards&#10;&#10;&#10;TIME SCALE:     approx. 3-5 years per turn&#10;MAP SCALE:     Point-to-point system&#10;UNIT SCALE:     Influence markers&#10;NUMBER OF PLAYERS:     2&#10;&#10;DESIGNER: Ananda Gupta &amp; Jason Matthews&#10;MAP, CARD, &amp; COUNTER ART: Mark Simonitch&#10;&#10;&#10;A deluxe edition, published in 2009 includes the following changes from the basic game:&#10;&#10;     Mounted map with revised graphics&#10;     Two double-thick counter sheets with 260 counters&#10;     Deck of 110 event cards (increased from 103)&#10;     Revised rules and player aid cards&#10;     Revised at start setup and text change for card #98 Aldrich Ames&#10;&#10;&#10;Upgrade kit for the owners of the previous version includes the following:&#10;&#10;     Mounted Map with revised graphics&#10;     New card decks&#10;     Updated Rules &amp; Charts&#10;&#10;&#10;",
              "rating": 8.07634,
              "year_published": 2005,
              "rank": 13,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 13,
              "thematic_rank": null,
              "wargames_rank": 2
          }
      },
      {
          "id": "14",
          "type": "board_games",
          "attributes": {
              "bgg_id": 182028,
              "title": "Through the Ages: A New Story of Civilization",
              "image_path": "https://cf.geekdo-images.com/fVwPntkJKgaEo0rIC0RwpA__original/img/1jawNpljTXwnT4km_2CjGwoUPR8=/0x0/filters:format(jpeg)/pic2663291.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 120,
              "max_playtime": 120,
              "categories": "Card Game, Civilization, Economic",
              "cooperative": false,
              "description": "Through the Ages: A New Story of Civilization is the new edition of Through the Ages: A Story of Civilization, with many changes small and large to the game's cards over its three ages and extensive changes to how military works.&#10;&#10;Through the Ages is a civilization building game. Each player attempts to build the best civilization through careful resource management, discovering new technologies, electing the right leaders, building wonders and maintaining a strong military. Weakness in any area can be exploited by your opponents. The game takes place throughout the ages beginning in the age of antiquity and ending in the modern age.&#10;&#10;One of the primary mechanisms in TTA is card drafting. Technologies, wonders, and leaders come into play and become easier to draft the longer they are in play. In order to use a technology you will need enough science to discover it, enough food to create a population to man it and enough resources (ore) to build the building to use it. While balancing the resources needed to advance your technology you also need to build a military. Military is built in the same way as civilian buildings. Players that have a weak military will be preyed upon by other players. There is no map in the game so you cannot lose territory, but players with higher military will steal resources, science, kill leaders, take population or culture. It is very difficult to win with a large military, but it is very easy to lose because of a weak one.&#10;&#10;Victory is achieved by the player whose nation has the most culture at the end of the modern age.&#10;&#10;",
              "rating": 8.07417,
              "year_published": 2015,
              "rank": 14,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 11,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "15",
          "type": "board_games",
          "attributes": {
              "bgg_id": 193738,
              "title": "Great Western Trail",
              "image_path": "https://cf.geekdo-images.com/u1l0gH7sb_vnvDvoO_QHqA__original/img/2zv_XMQoPFWk9Dn0oS4JY1IeFzw=/0x0/filters:format(jpeg)/pic4887376.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 75,
              "max_playtime": 150,
              "categories": "American West, Animals, Economic",
              "cooperative": false,
              "description": "America in the 19th century: You are a rancher and repeatedly herd your cattle from Texas to Kansas City, where you send them off by train. This earns you money and victory points. Needless to say, each time you arrive in Kansas City, you want to have your most valuable cattle in tow. However, the &quot;Great Western Trail&quot; not only requires that you keep your herd in good shape, but also that you wisely use the various buildings along the trail. Also, it might be a good idea to hire capable staff: cowboys to improve your herd, craftsmen to build your very own buildings, or engineers for the important railroad line.&#10;&#10;If you cleverly manage your herd and navigate the opportunities and pitfalls of Great Western Trail, you surely will gain the most victory points and win the game.&#10;&#10;&mdash;description from the publisher&#10;&#10;",
              "rating": 8.04864,
              "year_published": 2016,
              "rank": 15,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 12,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "16",
          "type": "board_games",
          "attributes": {
              "bgg_id": 84876,
              "title": "The Castles of Burgundy",
              "image_path": "https://cf.geekdo-images.com/5CFwjd8zTcGYVUnkXh04hw__original/img/N8btACZrnEYK1amBNk26VBdcGwc=/0x0/filters:format(jpeg)/pic1176894.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 30,
              "max_playtime": 90,
              "categories": "Dice, Medieval, Territory Building",
              "cooperative": false,
              "description": "The game is set in the Burgundy region of High Medieval France. Each player takes on the role of an aristocrat, originally controlling a small princedom. While playing they aim to build settlements and powerful castles, practice trade along the river, exploit silver mines, and use the knowledge of travelers.&#10;&#10;The game is about players taking settlement tiles from the game board and placing them into their princedom which is represented by the player board. Every tile has a function that starts when the tile is placed in the princedom. The princedom itself consists of several regions, each of which demands its own type of settlement tile.&#10;&#10;The game is played in five phases, each consisting of five rounds.  Each phase begins with the game board stocked with settlement tiles and goods tiles.  At the beginning of each round all players roll their two dice, and the player who is currently first in turn order rolls a goods placement die.  A goods tile is made available on the game board according to the roll of the goods die.  During each round players take their turns in the current turn order.  During his turn, a player may perform any two of the four possible types of actions: 1) take a settlement tile from the numbered depot on the game board corresponding to one of his dice and place it in the staging area on his player board, 2) take a settlement tile from the staging area of his player board to a space on his player board with a number matching one of his dice in the corresponding region for the type of tile and adjacent to a previously placed settlement tile, 3) deliver goods with a number matching one of his dice, or 4) take worker tokens which allow the player to adjust the roll of his dice.  In addition to these actions a player may buy a settlement tile from the central depot on the game board and place it in the staging area on his player board.  If an action triggers the award of victory points, those points are immediately recorded.  Each settlement tile offers a benefit, additional actions, additional money, advancement on the turn order track, more goods tiles, die roll adjustment or victory points.  Bonus victory points are awarded for filling a region with settlement tiles.&#10;&#10;The game ends after the fifth phase is played to completion.  Victory points are awarded for unused money and workers, and undelivered goods.  Bonus victory points from certain settlement tiles are awarded at the end of the game.&#10;&#10;The player with the most victory points wins.&#10;&#10;The rules include basic and advanced versions.&#10;&#10;This game is #14 in the Alea big box series.&#10;&#10;There is a separate BGG entry for the 2019 edition: The Castles of Burgundy.  The 2019 edition includes, alongside the base game, eight expansions, seven of which had already been released separately as promotional items and one new to the 2019 release.&#10;&#10;UPC 4005556812431&#10;&#10;",
              "rating": 8.00834,
              "year_published": 2011,
              "rank": 16,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 16,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "17",
          "type": "board_games",
          "attributes": {
              "bgg_id": 169786,
              "title": "Scythe",
              "image_path": "https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__original/img/HlDb9F365w0tSP8uD1vf1pfniQE=/0x0/filters:format(jpeg)/pic3163924.jpg",
              "min_players": 1,
              "max_players": 5,
              "min_playtime": 90,
              "max_playtime": 115,
              "categories": "Economic, Fighting, Science Fiction, Territory Building",
              "cooperative": false,
              "description": "It is a time of unrest in 1920s Europa. The ashes from the first great war still darken the snow. The capitalistic city-state known simply as &ldquo;The Factory&rdquo;, which fueled the war with heavily armored mechs, has closed its doors, drawing the attention of several nearby countries.&#10;&#10;Scythe is an engine-building game set in an alternate-history 1920s period. It is a time of farming and war, broken hearts and rusted gears, innovation and valor. In Scythe, each player represents a character from one of five factions of Eastern Europe who are attempting to earn their fortune and claim their faction's stake in the land around the mysterious Factory. Players conquer territory, enlist new recruits, reap resources, gain villagers, build structures, and activate monstrous mechs.&#10;&#10;Each player begins the game with different resources (power, coins, combat acumen, and popularity), a different starting location, and a hidden goal. Starting positions are specially calibrated to contribute to each faction&rsquo;s uniqueness and the asymmetrical nature of the game (each faction always starts in the same place). Scythe uses a streamlined action-selection mechanism (no rounds or phases) to keep gameplay moving at a brisk pace and reduce downtime between turns. While there is plenty of direct conflict for players who seek it, there is no player elimination.&#10;&#10;Scythe gives players almost complete control over their fate. Other than each player&rsquo;s individual hidden objective card, the only elements of luck or variability are &ldquo;encounter&rdquo; cards that players will draw as they interact with the citizens of newly explored lands. Each encounter card provides the player with several options, allowing them to mitigate the luck of the draw through their selection. Combat is also driven by choices, not luck or randomness. Every part of Scythe has an aspect of engine-building to it. Players can upgrade actions to become more efficient, build structures that improve their position on the map, enlist new recruits to enhance character abilities, activate mechs to deter opponents from invading, and expand their borders to reap greater types and quantities of resources. These engine-building aspects create a sense of momentum and progress throughout the game. The order in which players improve their engine adds to the unique feel of each game, even when playing one faction multiple times.&#10;&#10;",
              "rating": 8.00652,
              "year_published": 2016,
              "rank": 17,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 19,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "18",
          "type": "board_games",
          "attributes": {
              "bgg_id": 173346,
              "title": "7 Wonders Duel",
              "image_path": "https://cf.geekdo-images.com/zdagMskTF7wJBPjX74XsRw__original/img/Ju836WNSaW7Mab9Vjq2TJ_FqhWQ=/0x0/filters:format(jpeg)/pic2576399.jpg",
              "min_players": 2,
              "max_players": 2,
              "min_playtime": 30,
              "max_playtime": 30,
              "categories": "Ancient, Card Game, City Building, Civilization, Economic",
              "cooperative": false,
              "description": "In many ways 7 Wonders Duel resembles its parent game 7 Wonders as over three ages players acquire cards that provide resources or advance their military or scientific development in order to develop a civilization and complete wonders.&#10;&#10;What's different about 7 Wonders Duel is that, as the title suggests, the game is solely for two players, with the players not drafting cards simultaneously from hands of cards, but from a display of face-down and face-up cards arranged at the start of a round. A player can take a card only if it's not covered by any others, so timing comes into play as well as bonus moves that allow you to take a second card immediately. As in the original game, each card that you acquire can be built, discarded for coins, or used to construct a wonder.&#10;&#10;Each player starts with four wonder cards, and the construction of a wonder provides its owner with a special ability. Only seven wonders can be built, though, so one player will end up short.&#10;&#10;Players can purchase resources at any time from the bank, or they can gain cards during the game that provide them with resources for future building; as you acquire resources, the cost for those particular resources increases for your opponent, representing your dominance in this area.&#10;&#10;A player can win 7 Wonders Duel in one of three ways: each time you acquire a military card, you advance the military marker toward your opponent's capital, giving you a bonus at certain positions; if you reach the opponent's capital, you win the game immediately; similarly, if you acquire any six of seven different scientific symbols, you achieve scientific dominance and win immediately; if none of these situations occurs, then the player with the most points at the end of the game wins.&#10;&#10;",
              "rating": 7.97223,
              "year_published": 2015,
              "rank": 18,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 22,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "19",
          "type": "board_games",
          "attributes": {
              "bgg_id": 246900,
              "title": "Eclipse: Second Dawn for the Galaxy",
              "image_path": "https://cf.geekdo-images.com/Oh3kHw6lweg6ru71Q16h2Q__original/img/yW7d4RNfU1ndISCaPlfGYUyxnRU=/0x0/filters:format(jpeg)/pic5235277.jpg",
              "min_players": 2,
              "max_players": 6,
              "min_playtime": 60,
              "max_playtime": 200,
              "categories": "Civilization, Exploration, Science Fiction, Space Exploration, Wargame",
              "cooperative": false,
              "description": "A game of Eclipse places you in control of a vast interstellar civilization, competing for success with its rivals. You explore new star systems, research technologies, and build spaceships with which to wage war. There are many potential paths to victory, so you need to plan your strategy according to the strengths and weaknesses of your species, while paying attention to the other civilizations' endeavors.&#10;&#10;Eclipse: Second Dawn for the Galaxy is a revised and upgraded version of the Eclipse base game that debuted in 2011 that features:&#10;&#10;&#10;    New graphic design, while maintaining the acclaimed symbology of the first edition &#10;    A full line of Ship Pack 1 miniatures&#10;    New miniatures for ancients, GCDS, orbitals, and more&#10;    Custom plastic inlays&#10;    Custom combat dice&#10;    Fine-tuned gameplay&#10;&#10;&#10;",
              "rating": 7.96999,
              "year_published": 2020,
              "rank": 19,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 14,
              "thematic_rank": null,
              "wargames_rank": null
          }
      },
      {
          "id": "20",
          "type": "board_games",
          "attributes": {
              "bgg_id": 28720,
              "title": "Brass: Lancashire",
              "image_path": "https://cf.geekdo-images.com/tHVtPzu82mBpeQbbZkV6EA__original/img/3ffdJj5Pz6HQrg09Kh8ecTen-TY=/0x0/filters:format(jpeg)/pic3469216.jpg",
              "min_players": 2,
              "max_players": 4,
              "min_playtime": 60,
              "max_playtime": 120,
              "categories": "Economic, Industry / Manufacturing, Post-Napoleonic, Transportation",
              "cooperative": false,
              "description": "Brass: Lancashire &mdash; first published as Brass &mdash; is an economic strategy game that tells the story of competing cotton entrepreneurs in Lancashire during the industrial revolution. You must develop, build, and establish your industries and network so that you can capitalize demand for iron, coal and cotton. The game is played over two halves: the canal phase and the rail phase. To win the game, score the most victory points (VPs), which are counted at the end of each half. VPs are gained from your canals, rails, and established (flipped) industry tiles. Each round, players take turns according to the turn order track, receiving two actions to perform any of the following:&#10;&#10;&#10;    Build an industry tile&#10;    Build a rail or canal&#10;    Develop an industry&#10;    Sell cotton&#10;    Take a loan&#10;&#10;&#10;At the end of a player's turn, they replace the two cards they played with two more from the deck. Turn order is determined by how much money a player spent on the previous turn, from lowest spent first to highest spent. This turn order mechanism opens some strategic options for players going later in the turn order, allowing for the possibility of back-to-back turns.&#10;&#10;After all the cards have been played the first time (with the deck size being adjusted for the number of players), the canal phase ends and a scoring round commences. After scoring, all canals and all of the lowest level industries are removed for the game, after which new cards are dealt and the rail phase begins. During this phase, players may now occupy more than one location in a city and a double-connection build (though expensive) is possible. At the end of the rail phase, another scoring round takes place, then a winner is crowned.&#10;&#10;The cards limit where you can build your industries, but any card can be used for the develop, sell cotton or build connections actions. This leads to a strategic timing/storing of cards. Resources are common so that if one player builds a rail line (which requires coal) they have to use the coal from the nearest source, which may be an opponent's coal mine, which in turn gets that coal mine closer to scoring (i.e., being utilized).&#10;&#10;Brass: Lancashire, the 2018 edition from Roxley Games, reboots the original Warfrog Games edition of Brass with new artwork and components, as well as a few rules changes:&#10;&#10;&#10;     The virtual link rules between Birkenhead have been made optional.&#10;     The three-player experience has been brought closer to the ideal experience of four players by shortening each half of the game by one round and tuning the deck and distant market tiles slightly to ensure a consistent experience.&#10;     Two-player rules have been created and are playable without the need for an alternate board.&#10;     The level 1 cotton mill is now worth 5 VP to make it slightly less terrible.&#10;&#10;&#10;",
              "rating": 7.96226,
              "year_published": 2007,
              "rank": 20,
              "abstracts_rank": null,
              "cgs_rank": null,
              "childrens_games_rank": null,
              "family_games_rank": null,
              "party_games_rank": null,
              "strategy_games_rank": 15,
              "thematic_rank": null,
              "wargames_rank": null
          }
      }
  ]
}

export default mockGames